// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    created_by,
    name,
    type,
    balance,
    currency,
    color,
    meta
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, type, balance, currency, color, meta, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	CreatedBy *uuid.UUID     `json:"created_by"`
	Name      string         `json:"name"`
	Type      ACCOUNTTYPE    `json:"type"`
	Balance   pgtype.Numeric `json:"balance"`
	Currency  string         `json:"currency"`
	Color     COLORENUM      `json:"color"`
	Meta      []byte         `json:"meta"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.CreatedBy,
		arg.Name,
		arg.Type,
		arg.Balance,
		arg.Currency,
		arg.Color,
		arg.Meta,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Color,
		&i.Meta,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET
    deleted_at = current_timestamp
WHERE id = $1
RETURNING id, name, type, balance, currency, color, meta, created_by, updated_by, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountById = `-- name: GetAccountById :one
SELECT
    id,
    name,
    type,
    balance,
    currency,
    meta,
    color,
    created_by,
    updated_at
FROM accounts
WHERE id = $1 LIMIT 1
`

type GetAccountByIdRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Type      ACCOUNTTYPE    `json:"type"`
	Balance   pgtype.Numeric `json:"balance"`
	Currency  string         `json:"currency"`
	Meta      []byte         `json:"meta"`
	Color     COLORENUM      `json:"color"`
	CreatedBy *uuid.UUID     `json:"created_by"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetAccountById(ctx context.Context, id uuid.UUID) (GetAccountByIdRow, error) {
	row := q.db.QueryRow(ctx, getAccountById, id)
	var i GetAccountByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Meta,
		&i.Color,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccounts = `-- name: GetAccounts :many
SELECT
    id,
    name,
    type,
    balance,
    currency,
    color,
    meta,
    updated_at
FROM accounts
WHERE created_by = $1
`

type GetAccountsRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Type      ACCOUNTTYPE    `json:"type"`
	Balance   pgtype.Numeric `json:"balance"`
	Currency  string         `json:"currency"`
	Color     COLORENUM      `json:"color"`
	Meta      []byte         `json:"meta"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetAccounts(ctx context.Context, userID *uuid.UUID) ([]GetAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsRow{}
	for rows.Next() {
		var i GetAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Balance,
			&i.Currency,
			&i.Color,
			&i.Meta,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    name = coalesce($1, name),
    type = coalesce($2, type),
    balance = coalesce($3, balance),
    currency = coalesce($4, currency),
    color = coalesce($5, color),
    meta = coalesce($6, meta),
    updated_by = $7
WHERE id = $8
RETURNING id, name, type, balance, currency, color, meta, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateAccountParams struct {
	Name      *string         `json:"name"`
	Type      NullACCOUNTTYPE `json:"type"`
	Balance   pgtype.Numeric  `json:"balance"`
	Currency  *string         `json:"currency"`
	Color     NullCOLORENUM   `json:"color"`
	Meta      []byte          `json:"meta"`
	UpdatedBy *uuid.UUID      `json:"updated_by"`
	ID        uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Balance,
		arg.Currency,
		arg.Color,
		arg.Meta,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Color,
		&i.Meta,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = balance + $2
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}
