// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/Fantasy-Programming/nuts/internal/repository/dto"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ACCOUNTTYPE string

const (
	ACCOUNTTYPECash       ACCOUNTTYPE = "cash"
	ACCOUNTTYPEMomo       ACCOUNTTYPE = "momo"
	ACCOUNTTYPECredit     ACCOUNTTYPE = "credit"
	ACCOUNTTYPEInvestment ACCOUNTTYPE = "investment"
	ACCOUNTTYPEChecking   ACCOUNTTYPE = "checking"
	ACCOUNTTYPESavings    ACCOUNTTYPE = "savings"
	ACCOUNTTYPELoan       ACCOUNTTYPE = "loan"
	ACCOUNTTYPEOther      ACCOUNTTYPE = "other"
)

func (e *ACCOUNTTYPE) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ACCOUNTTYPE(s)
	case string:
		*e = ACCOUNTTYPE(s)
	default:
		return fmt.Errorf("unsupported scan type for ACCOUNTTYPE: %T", src)
	}
	return nil
}

type NullACCOUNTTYPE struct {
	ACCOUNTTYPE ACCOUNTTYPE `json:"ACCOUNT_TYPE"`
	Valid       bool        `json:"valid"` // Valid is true if ACCOUNTTYPE is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullACCOUNTTYPE) Scan(value interface{}) error {
	if value == nil {
		ns.ACCOUNTTYPE, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ACCOUNTTYPE.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullACCOUNTTYPE) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ACCOUNTTYPE), nil
}

func (e ACCOUNTTYPE) Valid() bool {
	switch e {
	case ACCOUNTTYPECash,
		ACCOUNTTYPEMomo,
		ACCOUNTTYPECredit,
		ACCOUNTTYPEInvestment,
		ACCOUNTTYPEChecking,
		ACCOUNTTYPESavings,
		ACCOUNTTYPELoan,
		ACCOUNTTYPEOther:
		return true
	}
	return false
}

type COLORENUM string

const (
	COLORENUMRed   COLORENUM = "red"
	COLORENUMGreen COLORENUM = "green"
	COLORENUMBlue  COLORENUM = "blue"
)

func (e *COLORENUM) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = COLORENUM(s)
	case string:
		*e = COLORENUM(s)
	default:
		return fmt.Errorf("unsupported scan type for COLORENUM: %T", src)
	}
	return nil
}

type NullCOLORENUM struct {
	COLORENUM COLORENUM `json:"COLOR_ENUM"`
	Valid     bool      `json:"valid"` // Valid is true if COLORENUM is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCOLORENUM) Scan(value interface{}) error {
	if value == nil {
		ns.COLORENUM, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.COLORENUM.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCOLORENUM) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.COLORENUM), nil
}

func (e COLORENUM) Valid() bool {
	switch e {
	case COLORENUMRed,
		COLORENUMGreen,
		COLORENUMBlue:
		return true
	}
	return false
}

type Account struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Type      ACCOUNTTYPE        `json:"type"`
	Balance   pgtype.Numeric     `json:"balance"`
	Currency  string             `json:"currency"`
	Color     COLORENUM          `json:"color"`
	Meta      []byte             `json:"meta"`
	CreatedBy *uuid.UUID         `json:"created_by"`
	UpdatedBy *uuid.UUID         `json:"updated_by"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	ParentID  *uuid.UUID         `json:"parent_id"`
	IsDefault *bool              `json:"is_default"`
	CreatedBy uuid.UUID          `json:"created_by"`
	UpdatedBy *uuid.UUID         `json:"updated_by"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Currency struct {
	Code string  `json:"code"`
	Name *string `json:"name"`
}

type LinkedAccount struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	Email          *string   `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
}

type Preference struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Locale            string             `json:"locale"`
	Theme             string             `json:"theme"`
	Currency          string             `json:"currency"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Timezone          string             `json:"timezone"`
	TimeFormat        string             `json:"time_format"`
	DateFormat        string             `json:"date_format"`
	StartWeekOnMonday bool               `json:"start_week_on_monday"`
	DarkSidebar       bool               `json:"dark_sidebar"`
}

type Tag struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Color  COLORENUM `json:"color"`
}

type Transaction struct {
	ID                   uuid.UUID          `json:"id"`
	Amount               pgtype.Numeric     `json:"amount"`
	Type                 string             `json:"type"`
	AccountID            uuid.UUID          `json:"account_id"`
	CategoryID           uuid.UUID          `json:"category_id"`
	DestinationAccountID *uuid.UUID         `json:"destination_account_id"`
	TransactionDatetime  time.Time          `json:"transaction_datetime"`
	Description          *string            `json:"description"`
	Details              dto.Details        `json:"details"`
	CreatedBy            *uuid.UUID         `json:"created_by"`
	UpdatedBy            *uuid.UUID         `json:"updated_by"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	FirstName     *string            `json:"first_name"`
	LastName      *string            `json:"last_name"`
	Password      *string            `json:"password"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	AvatarUrl     *string            `json:"avatar_url"`
	MfaSecret     []byte             `json:"mfa_secret"`
	MfaEnabled    bool               `json:"mfa_enabled"`
	MfaVerifiedAt pgtype.Timestamptz `json:"mfa_verified_at"`
}

type UserToken struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    time.Time          `json:"expires_at"`
	LastUsedAt   time.Time          `json:"last_used_at"`
	UserAgent    *string            `json:"user_agent"`
	IpAddress    *string            `json:"ip_address"`
	IsCurrent    *bool              `json:"is_current"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Location     *string            `json:"location"`
	BrowserName  *string            `json:"browser_name"`
	DeviceName   *string            `json:"device_name"`
	OsName       *string            `json:"os_name"`
	Revoked      *bool              `json:"revoked"`
}

type WebhookEvent struct {
	ID             uuid.UUID        `json:"id"`
	SubscriptionID uuid.UUID        `json:"subscription_id"`
	EventType      string           `json:"event_type"`
	Payload        []byte           `json:"payload"`
	Status         *string          `json:"status"`
	Attempts       *int32           `json:"attempts"`
	LastAttempt    pgtype.Timestamp `json:"last_attempt"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type WebhookSubscription struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Event       []string         `json:"event"`
	Active      bool             `json:"active"`
	EndpointUrl string           `json:"endpoint_url"`
	Secret      string           `json:"secret"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
