version: "3"

tasks:
  default:
    desc: Lists available commands
    cmds:
      - task -l
  list:
    desc: Lists available commands
    cmds:
      - task -l

  migrate:create:
    desc: Creates .sql migration files (Up and Down). Set name by appending with 'NAME=name_of_file'
    cmds:
      - goose -dir database/migrations create "{{.NAME}}" sql


  migrate:
    desc: Migrates UP the database
    cmds:
      - goose -dir database/migrations up

  migrate:status:
    desc: Get the status of your migrations
    cmds:
      - goose -dir database/migrations status

  migrate:step:
    desc: Migrates UP bt one step the database
    cmds:
      - goose -dir database/migrations up-by-one

  migrate:rollback:
    desc: Rollback the database by one step
    cmds:
      - goose -dir database/migrations down

  check:
    desc: Checks integrity of program
    cmds:
      - task generate
      - task swagger
      - task fmt
      - task vet
      - task lint
      - task vuln
      - task test
    silent: true

  run:
    desc: Runs the app
    cmds:
      - task: swagger
      - go run cmd/api/main.go
    silent: true

  dev:
    desc: Hot reload. Watch for file changes and rebuild binary.
    cmds:
      - air
    silent: true

  build:
    desc: Creates a compiled binary and copy configuration files into ./bin
    vars:
      GIT_TAG:
        sh: git describe --abbrev=0 --tags
      GIT_COMMIT:
        sh: git rev-list -1 HEAD
    cmds:
      - task: check
      - go build -ldflags="-X main.Version={{.GIT_TAG}}-{{.GIT_COMMIT}} -s"  -o go8 cmd/go8/main.go
      - mkdir -p bin
      - mv go8 bin/
      - cp .env bin
    silent: false

  routes:
    desc: List all registered routes.
    silent: true
    cmds:
      - go run cmd/route/main.go

  clean:
    desc: Clears built files and tests
    cmds:
      - rm -rf ./bin/*
      - rm -rf ./bin/.*
      - task: test:clean:cache

  tidy:
    desc: Downloads dependencies and removes unused ones
    cmds:
      - go mod tidy

  vet:
    desc: Vets code
    cmds:
      - go vet ./...

  lint:
    desc: Uses golangci-lint
    cmds:
      - golangci-lint run

  vuln:
    desc: Run Go Vulnerability Check
    cmds:
      - govulncheck ./...

  fmt:
    desc: Reformat code
    cmds:
      - go fmt ./...

  test:
    desc: Test all code (unit and integration)
    cmds:
      - go test ./...

  test:unit:
    desc: Test only unit tests
    cmds:
      - go test -short ./...

  test:integration:
    desc: Test only integration tests
    cmds:
      - go test -run Integration ./...

  test:verbose:
    desc: Test all code with verbose mode
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Perform test coverage
    cmds:
      - go test -cover ./...

  test:slow:
    desc: Find slow running tests
    platforms: [ linux ]
    cmds:
      - go clean -testcache
      - go test -v -json ./... | jq -r 'select(.Action == "pass" and .Test != null) | .Test + "," + (.Elapsed | tostring)'  | sort -r -k2 -n -t, | head

  test:e2e:
    desc: Run e2e test
    dir: e2e
    cmds:
      - task: test:e2e:down # Ensures all containers are shut down for clean data directories
      - docker-compose -f e2e/docker-compose.yml up --build
    silent: true

  test:e2e:down:
    desc: Stops e2e test and remove the containers
    dir: e2e
    cmds:
      - docker-compose -f e2e/docker-compose.yml down -v

  race:
    desc: Check race condition
    cmds:
      - go test -race ./...

  test:clean:
    desc: Clear tests cache
    cmds:
      - go clean -testcache

  swagger:
    desc: Generates Swagger page for API reference
    cmds:
      - swag init -o internal/server/docs -g cmd/api/main.go
